### PR TITLE
Fixes #191

### LINKED ISSUE #191: SVG [Template] - consider reversed axis settings
Some charts required a reversed axis, e.g. NMR data, example Line Series 6:

Bildschirmfoto von 2020-07-03 07-22-23

The exported SVG should also print the data and axis reversed (x axis from positive to negative values):

Bildschirmfoto von 2020-07-03 08-08-36

The reversed axis setting is set as follows:

`primaryAxisSettingsX.setReversed(true);`

### PR DESCRIPTION
**Pull request by yashTEF**
Fixes #191 
Signed-off-by: yashTEF <yashsoc@gmail.com>

### CODE REVIEW

**Comment by eselmeister** [comment]
@yashTEF Flipping the axes is good, but the data series must be also flipped, see screenshots:

Bildschirmfoto von 2020-07-10 06-34-25

Have a look at the reference peak at ppm 0:

Bildschirmfoto von 2020-07-10 06-34-52

Bildschirmfoto von 2020-07-10 06-35-52

**Comment by yashTEF** [comment]
Untitled

**Comment by eselmeister** [comment]
@yashTEF The export is shifted now.

Bildschirmfoto von 2020-07-10 10-38-09

**Comment by yashTEF** [comment]
Untitled
Untitled3

**Pull request merged**
