### PR TITLE
Fixed #85-Buffering chart data via a Bitmap

### LINKED ISSUE #85: Buffering chart data via a Bitmap
Currently, charts are redrawn several times when actions are applied on the chart. in most cases, the data doesn't need to be redrawn as it not has changed. This causes some performance issues, especially when handling large data sets with many distinct points or when trying to select a region. A smart solution to solve this problem could be to create a bitmap initially, which is displayed in 1:1 or zoomed modus.

### PR DESCRIPTION
**Pull request by yashTEF**
Fixes #85 Bitmap now fits perfectly into the background of plot area
Signed-off-by: yashTEF <yashsoc@gmail.com>

### CODE REVIEW

**Comment by eselmeister** [comment]
@yashTEF Your approach goes in the right direction and it's a first good try. Let me list some issues I have discovered:

A) Cycle dependencies
Referencing the bundle "org.eclipse.swtchart.export" in "org.eclipse.swtchart.extensions" leads to a cycle dependency. That's a flaw and leads to a broken build. The bundle dependency in SWTChart is as follows:

- org.eclipse.swtchart
- org.eclipse.swtchart.extensions
- org.eclipse.swtchart.export

The dependency to the export bundle is not really needed as the image creation could be also implemented in a simple way in the PlotArea. This has also the benefit, that no resizing of the image is needed as only the plot area is transferred to an image.

http://www.swtchart.org/doc/index.html#Chart_Plot_Area

B) Create Image in PlotArea
Place the code to create the image in the PlotArea "public ImageData getImageData() {...}". it automatically has the correct size. The paintControl method is modified too to exactly position the image:

```
if(image != null) {
	e.gc.drawImage(image, 0, 0);
}
```

C) Handle Selection
The idea to put the image creation and buffering in the BaseChart was a good idea. Unfortunately, it does not have the intended effect. You can leave the BaseChart as it is. Rather put the code to create and buffer the selection in the handler(s) when the selection starts/ends.

org.eclipse.swtchart.extensions.events.MouseDownEvent
org.eclipse.swtchart.extensions.events.MouseUpEvent

D) Series Visibility
In the mouse up event, all series are set to visible = true. It could be, that the user has set some series manually in the status visible = false, see Interactive Legend:

https://github.com/eclipse/swtchart/issues/137

Hence, only series that were visible before shall be set visible again. All hidden series shall stay hidden. When using the series, please also add the generic extension: ISeries<?>.

E) IChartSettings
The chart settings shall offer an option to enable/disable the buffering. By default it shall be disabled, until we have tested it on several systems Windows, macOS and Linux.

F) Testing
LineSeries_4_Part could be used to test the effect of "setBufferSelection(true)" or "setBufferSelection(false)".

The above points A) - F) are addressed in the following branch:
https://github.com/eclipse/swtchart/tree/Issue%2385

Please have a look and make your adjustments, especially regarding D).

**Comment by yashTEF** [comment]
Hi Philip,
I made the requested adjustments as shown in -
https://github.com/eclipse/swtchart/tree/Issue%2385
,I have resolved the issue D) but I'm not completely sure whether its the right approach.
Would love to get your feedback.
Thanks,
Yash

**Comment by eselmeister** [comment]
@yashTEF Your changes are looking good. In a very unlikely case, a NPE could occur. This could happen if the MouseDown event handler is not called, but the MouseUp event handler. In such a case, the call

`Set<String> set = MouseDownEvent.getVisibleSeriesId();`

would cause a NPE. Please read to the end until you start changing the code. I'll not present a ready solution instantly, but try to develop the idea how to solve it with you. The first step would be to initialize the set and clear "visibleSeriesId.clear()" it before populating it. This ensures that the set is never null:

`private static Set<String> visibleSeriesId = new HashSet<String>();`

The code, which adds the visible series, should be moved inside of the block "if(baseChart.getChartSettings().isBufferSelection()) {...}". 

```
ISeriesSet set = baseChart.getSeriesSet();
ISeries<?>[] series = set.getSeries();
visibleSeriesId.clear();
for(ISeries<?> serie : series) {
	if(serie.isVisible()) {
		visibleSeriesId.add(serie.getId());
	}
	baseChart.hideSeries(serie.getId());
}
```

But using a static member could lead to strange behavior.  The mouse down and up event happens in the UI thread. But all mouse down and up events of all charts share in this case one static member of the visibleSeriesId. It can't be ensured that the correct ids are fetched. In synchronized UI actions, it's unlikely, but in async actions, this could happen. Hence, the visibleSeriesId idea was a good starting point, but leads to some problem. Instead, the series object itself is unique and should hold the information of its internal status. You could extend the ISeries interface:

```
boolean isVisibleBuffered();
void setVisibleBuffered(boolean visibleBuffered);
```

And make an implementation in `org.eclipse.swtchart.internal.series.Series` which is by default `visibleBuffered = false`. When running the mouse down event, you could simply call:

```
for(ISeries<?> serie : series) {
	serie.setVisibleBuffered(serie.isVisible());
	baseChart.hideSeries(serie.getId());
} 
```

And in the mouse up event just call:

```
ISeriesSet set = baseChart.getSeriesSet();
ISeries<?>[] series = set.getSeries();
for(ISeries<?> serie : series) {
	if(serie.isVisibleBuffered()) {
		baseChart.showSeries(serie.getId());
		serie.setVisibleBuffered(false);
	}
}
```

This ensures that you always handle the correct ids and series.

**Comment by eselmeister** [comment]
@yashTEF I'll be back on Tuesday morning to review your new changes.

**Pull request merged**
