### PR TITLE
Updated to Java 11

### LINKED ISSUE #253: Java 11
https://www.oracle.com/java/technologies/java-se-support-roadmap.html Java 8 is EOL, it is in extended support for commercial customers. https://twitter.com/akurtakov/status/1410577466016649223 did a poll which indicates that Eclipse SWT will drop Java 8 soon as well. There was already interest to compile using the current LTS release Java 11. https://github.com/eclipse/swtchart/pull/110 layed some groundwork to this. Before going even further https://github.com/eclipse/swtchart/issues/252 we should have at least one release targeting current Java LTS.

### PR DESCRIPTION
**Pull request by Mailaender**
Depends on https://github.com/eclipse/swtchart/pull/273
Closes https://github.com/eclipse/swtchart/issues/253

### CODE REVIEW

**Comment by Mailaender** [comment]
Ping @akurtakov

**Comment by akurtakov** [comment]
> Ping @akurtakov

Sorry for late reply. What do you ask of me ?

**Comment by Mailaender** [comment]
You made some previous Java 11 related changes (thanks!) so I thought you might be interested.

**Comment by akurtakov** [comment]
Thanks! Unfortunately I haven't had time to look into our usage of swtchart lately.

**Comment by akurtakov** [comment]
@eselmeister I guess this is for you

**Comment by eselmeister** [comment]
Yep, the try to migrate to Java 11 this week.

**Pull request merged**
