### PR TITLE
Add setLimitRange() method to the IAxis interface

### PR DESCRIPTION
**Pull request by QuocDoBV**
Add setLimitRange() method to the IAxis interface

### CODE REVIEW

**Comment by eselmeister** [comment]
@QuocDoBV Did you use the same credentials as in the PR before? The ECA check fails currently.

**Comment by QuocDoBV** [comment]
> @QuocDoBV Did you use the same credentials as in the PR before? The ECA check fails currently.

I don't change ECA recently. I am trying to fix the ECA check.

**Comment by eselmeister** [comment]
@QuocDoBV You need to sign the commit with the email used in the ECA. If you use another email in the commit, then the ECA check fails.

**Comment by QuocDoBV** [comment]
> @QuocDoBV You need to sign the commit with the email used in the ECA. If you use another email in the commit, then the ECA check fails.

I have updated the email to the same as the last PR but the ECA still have not fixed yet.
image
image

**Comment by QuocDoBV** [comment]
> @QuocDoBV The easiest if you skip this PR and create a new one. Take care that the commit is signed off with your username `QuocDoBV` and email `@users.noreply.github.com` used in the ECA.

Thank you, I will close this PR and create a new one instead.

**Comment by QuocDoBV** [comment]
> `@users.noreply.github.com` is just what the @github interfaces shows for privacy reasons. You need to state your real e-Mail address. Use [git-commit --author](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---authorltauthorgt) to change the e-Mail of an existing commit.

Thank you for your advice! I have resolved them.

**Pull request closed without merging**
