### PR TITLE
Revert "Disable .jar signing for now"

### PR DESCRIPTION
**Pull request by akurtakov**
This reverts commit 715a493ea5bc0ce32eba758c980b9b44bc7e9c9d.

### CODE REVIEW

**Comment by akurtakov** [comment]
@eselmeister Let me know if there are issues with this patch as I don't see Jenkins build for PRs.

**Comment by Mailaender** [comment]
This will probably fail https://ci.eclipse.org/swtchart/job/build/job/REL-0.13.0/663/

**Comment by akurtakov** [comment]
What you point to uses jarsigner plugin 1.1.7, which is broken due to change in signing service . One has to use 1.3.0+ (1.3.2 is the latest) to get it to point to new signing service.

**Comment by akurtakov** [comment]
But this is another branch, signing "develop" should work.

**Comment by eselmeister** [comment]
Probably, it works on develop.

**Comment by eselmeister** [comment]
Also this crashes

```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:2.7.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.eclipse.tycho:tycho-maven-plugin:jar:2.7.4 @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.eclipse.swtchart:org.eclipse.swtchart.build:0.14.0 (/home/jenkins/agent/workspace/build_develop/org.eclipse.swtchart.cbi/pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:2.7.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.eclipse.tycho:tycho-maven-plugin:jar:2.7.4: Could not transfer artifact org.eclipse.tycho:tycho-maven-plugin:pom:2.7.4 from/to eclipse (https://repo.eclipse.org/content/repositories/cbi/): transfer failed for https://repo.eclipse.org/content/repositories/cbi/org/eclipse/tycho/tycho-maven-plugin/2.7.4/tycho-maven-plugin-2.7.4.pom, status: 502 Bad Gateway -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException
```

**Comment by eselmeister** [comment]
Each and every run, new errors:
```

[INFO] Scanning for projects...
[WARNING] Could not validate integrity of download from https://repo.eclipse.org/content/repositories/maven_central/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.pom
org.eclipse.aether.transfer.ChecksumFailureException: Checksum validation failed, no checksums available

```

**Comment by eselmeister** [comment]
`
[ERROR] Failed to execute goal org.eclipse.cbi.maven.plugins:eclipse-jarsigner-plugin:1.3.2:sign (sign) on project org.eclipse.swtchart.build: Execution sign of goal org.eclipse.cbi.maven.plugins:eclipse-jarsigner-plugin:1.3.2:sign failed: Plugin org.eclipse.cbi.maven.plugins:eclipse-jarsigner-plugin:1.3.2 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.cbi.maven.plugins:eclipse-jarsigner-plugin:jar:1.3.2 -> org.apache.maven:maven-core:jar:3.8.1 -> org.apache.maven:maven-repository-metadata:jar:3.8.1: Failed to read artifact descriptor for org.apache.maven:maven-repository-metadata:jar:3.8.1: Could not transfer artifact org.apache.maven:maven-repository-metadata:pom:3.8.1 from/to eclipse (https://repo.eclipse.org/content/repositories/cbi/): transfer failed for https://repo.eclipse.org/content/repositories/cbi/org/apache/maven/maven-repository-metadata/3.8.1/maven-repository-metadata-3.8.1.pom, status: 502 Bad Gateway -> [Help 1]
`

**Comment by eselmeister** [comment]
502 Bad Gateway

**Comment by eselmeister** [comment]
It seems that the Eclipse build infrastructure is instable at the moment.

**Comment by akurtakov** [comment]
You should report the issue with swtchart JIPP to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/new

**Pull request merged**
