### PR TITLE
Added new Mouse Down Event Listener for CircularCharts

### PR DESCRIPTION
**Pull request by himanshu-balasamanta**
code is cleaner, and user has the choice to set the setting if or not he wants the redrawn charts to use the entire space available.

`circularSeriesSettings.setFillEntireSpace(boolean fillEntireSpace);` is false by default, setting it to true leads to filling up the entire space available.

### CODE REVIEW

**Comment by eselmeister** [comment]
@Himanshu-Balasamanta Please address the following issues:

`BaseChart.java `
The following code could be called once. An additional check that the object is instanceof CircularMouseDownEvent should be added.
`((CircularMouseDownEvent)registeredEvents.get(EVENT_MOUSE_DOWN).get(1).get(SWT.NONE).get(0))...`

`CircularMouseDownEvent.java`
Please add the Header.

`PieChart.java`
-> The code is fine, but we use to put the subroutine in curly brackets.
if(handledEventProcessor != null) {
	chartSettings.removeHandledEventProcessor(handledEventProcessor);
}

I will also add a method in the settings to remove a registered handler by class name. That makes it easier to remove/exchange event processors.

**Comment by himanshu-balasamanta** [comment]
Hi,
As there already is a 
`ChartSettings.removeHandledEventProcessor(IHandledEventProcessor handledEventProcessor);` 
and a 
`ChartSettings.addHandledEventProcessor(IHandledEventProcessor handledEventProcessor);`
it may be better to add a method 
`ChartSettings.getHandledEventProcessorByClass()`
 to it instead.

**Comment by eselmeister** [comment]
@Himanshu-Balasamanta Yep, adding a method `ChartSettings.getHandledEventProcessorByClass()` is a good idea.

**Comment by eselmeister** [comment]
I will add the method `ChartSettings.getHandledEventProcessorByClass()`.

**Pull request merged**
