### PR TITLE
Closes: #170

### PR DESCRIPTION
**Pull request by himanshu-balasamanta**
- Legend Support added for Multi-Level Pie Chart.
- HSB Colouring added to simple and multi-level pie chart to enable smooth colour transition across the chart.
- MultiLevel Pie Chart APIs modified to cover all functionalities of Simple Level Pie Chart.

### CODE REVIEW

**Comment by himanshu-balasamanta** [comment]
simple
multi-Level

**Comment by eselmeister** [comment]
@Himanshu-Balasamanta In my workspace, running the PieChartExample fails, because the recangle "r" is null. It seems, that the legend is created too early. In your example, it works. Hence, let's see what the CI says.

```
for(int j = 0; j != labels.length; j++) {
	Rectangle r = cellBounds.get(labels[j]);
	drawPieSymbol(gc, labels[j], color[j], new Rectangle(r.x + MARGIN, r.y + MARGIN, SYMBOL_WIDTH, r.height - MARGIN * 2));
	gc.setBackground(getBackground());
	gc.setForeground(getForeground());
	gc.drawText(labels[j], r.x + SYMBOL_WIDTH + MARGIN * 2, r.y, true);
}
```
With a next PR, you could address to add the PieChart- and MultiLevelPieChart examples to `RunAllExamples`.

**Comment by himanshu-balasamanta** [comment]
@yashTEF  Please pull this commit and run the two chart examples in your workspace. Let us know if there is any error message generated in your version of eclipse.

**Comment by yashTEF** [comment]
> @yashTEF Please pull this commit and run the two chart examples in your workspace. Let us know if there is any error message generated in your version of eclipse.

yep, its running fine in my workspace too

**Pull request merged**
