### PR TITLE
Fix signing on REL-0.13.0

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by akurtakov** [comment]
@Mailaender Would you please try this one for the 0.13.0 branch?

**Comment by Mailaender** [comment]
Sorry, I don't have access.

**Comment by akurtakov** [comment]
@eselmeister I guess we are back to you.

**Comment by eselmeister** [comment]
Yes, I'll adjust the parameters on develop too.

**Comment by eselmeister** [comment]
It leads to a crashing build again. I'll try to fix it.

```
[WARNING] Could not validate integrity of download from https://repo.eclipse.org/content/repositories/maven_central/org/apache/maven/maven-core/3.0/maven-core-3.0.jar
org.eclipse.aether.transfer.ChecksumFailureException: Checksum validation failed, no checksums available
    at org.eclipse.aether.internal.impl.AbstractChecksumPolicy.onNoMoreChecksums (AbstractChecksumPolicy.java:64)
    at org.eclipse.aether.connector.basic.ChecksumValidator.validate (ChecksumValidator.java:107)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask (BasicRepositoryConnector.java:460)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:364)
    at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
[WARNING] Could not validate integrity of download from https://repo.eclipse.org/content/repositories/maven_central/org/eclipse/tycho/tycho-core/1.6.0/tycho-core-1.6.0.jar
org.eclipse.aether.transfer.ChecksumFailureException: Checksum validation failed, no checksums available
    at org.eclipse.aether.internal.impl.AbstractChecksumPolicy.onNoMoreChecksums (AbstractChecksumPolicy.java:64)
    at org.eclipse.aether.connector.basic.ChecksumValidator.validate (ChecksumValidator.java:107)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask (BasicRepositoryConnector.java:460)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:364)
    at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
[WARNING] Could not validate integrity of download from https://repo.eclipse.org/content/repositories/maven_central/org/apache/maven/maven-aether-provider/3.0/maven-aether-provider-3.0.jar
org.eclipse.aether.transfer.ChecksumFailureException: Checksum validation failed, no checksums available
    at org.eclipse.aether.internal.impl.AbstractChecksumPolicy.onNoMoreChecksums (AbstractChecksumPolicy.java:64)
    at org.eclipse.aether.connector.basic.ChecksumValidator.validate (ChecksumValidator.java:107)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask (BasicRepositoryConnector.java:460)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:364)
    at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
```

**Comment by akurtakov** [comment]
This happened on platform build too https://ci.eclipse.org/releng/job/I-build-4.25/97/console aka a general issue with JIPPs IMHO.

**Comment by akurtakov** [comment]
Next build worked so try restarting.

**Comment by eselmeister** [comment]
Restartet ... I have also updated to Tycho latest.

**Comment by eselmeister** [comment]
`Caused by: java.lang.UnsupportedClassVersionError: org/eclipse/tycho/core/maven/TychoMavenLifecycleParticipant has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

arrghh

**Comment by eselmeister** [comment]
It's so damned frustrating working with this build process ...

`aused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.ow2.asm:asm:jar:7.2, org.ow2.asm:asm-analysis:jar:7.2: Could not transfer artifact org.ow2.asm:asm:jar:7.2 from/to eclipse.maven.central.mirror (https://repo.eclipse.org/content/repositories/maven_central/): transfer failed for https://repo.eclipse.org/content/repositories/maven_central/org/ow2/asm/asm/7.2/asm-7.2.jar, status: 502 Bad Gateway
`

**Comment by eselmeister** [comment]
BUILD SUCCESS

**Pull request merged**
