### PR TITLE
GSOC PHASE 3 Vertical Slider Issue

### LINKED ISSUE #164: Vertical Slider Issue
The slider is a widget that returns a value in a linear range when slided.
The selection value is 0 at top and maximum at bottom. 
Currently, the vertical slider in SWTChart allocates y axis min for min selection value of slider. This leads to the slider working counter-intuitively.

### PR DESCRIPTION
**Pull request by himanshu-balasamanta**
Made changes so as the minimum of vertical slider selection corresponds to max axis value of the vertical Axis, and the max selection value corresponds to min axis value of vertical axis.

### CODE REVIEW

**Comment by himanshu-balasamanta** [comment]
Committed in tickets for better understanding, as incomplete pull request would be meaningless.
Consider this as my code for the third phase of GSoC.

**Review by eselmeister — CHANGES_REQUESTED** [review]
The code works as expected, but reading the code is counter intuitive. In this case, the range is created as follows:

`return new Range(max, min);`

The value max is always lower than min, but when reading the code, it's confusing as the first thought is, that a range should be created with the min value first. Please adjust the code, so that a reader better understands what happens here. 

Does the Y scrollbar also takes care of large values? Please have a look at the following issue:
https://github.com/eclipse/swtchart/issues/12

**Comment by himanshu-balasamanta** [comment]
I have brought the changes in naming of variables. As of issue #12  I am looking into it.

**Comment by eselmeister** [comment]
@Himanshu-Balasamanta The changes are fine. I have one additional change request. Please update the copyright header(s) to the current year, if touching/changing files. Some of the changed files still use 2019. Please update to e.g.:

`Copyright (c) 2017, 2019 ...`
->
`Copyright (c) 2017, 2020 ...`

**Pull request merged**
