### PR TITLE
Arbitrary base logarithmic scale scale

### PR DESCRIPTION
**Pull request by Sebdar**
Hello! I am currently using SWTChart in a different Eclipse project and needed to use a base-2 logarithmic scale on both axes.

I added two new public methods to the `IAxis` interface : 
- `void setLogScaleBase(double base)` to set a new base
- `double getLogScaleBase()` to get the current base

The default behaviour is unchanged, the axis will use a decimal logarithm by default. I added some test cases as well for potential invalid bases.
I would love to get some feedback on this (short) pull request.

Thank you!

### CODE REVIEW

**Comment by eselmeister** [comment]
@Sebdar Thanks for your interest in SWTChart and the PR. I will do a review soon.

**Comment by eselmeister** [comment]
Your PR looks fine. Thanks for providing this improvement. Two small issues need to be addressed:

Update the year in the copyright header of all changed files to 2022, e.g.:
` * Copyright (c) 2008, 2022 SWTChart project.`

Add yourself to the contributors list, e.g.:
```
 * Contributors:
 * yoshitaka - initial API and implementation
 * Philip Wenig - option to skip drawing the axis line
 * Sebastien Darche - Implement arbitrary base log scale
```

**Comment by Sebdar** [comment]
Thank you so much for your feedback. I just pushed the small modifications you requested

**Comment by eselmeister** [comment]
Thanks for supporting SWTChart!

**Pull request merged**
