### PR TITLE
StepChart created internally when adding data series:

### PR DESCRIPTION
**Pull request by yashTEF**
User now does not have to enable step every time to create  a
StepChart,now he can just set SeriesType as SeriesType.STEP
and steps will be enabled internally.

Signed-off-by: yashTEF <yashsoc@gmail.com>

### CODE REVIEW

**Comment by yashTEF** [comment]
The above can be done by code as follows-
```
ILineSeries lineSeries = (ILineSeries)chart.getSeriesSet().createSeries(SeriesType.STEP, "step series");
		lineSeries.setYSeries(ySeries);
		lineSeries.setSymbolType(PlotSymbolType.NONE);
```

**Comment by eselmeister** [comment]
@yashTEF Please enable the "Save Actions" to format the source code. The code styles are already included in the project. You only have to enable the option in Eclipse:

Bildschirmfoto vom 2020-03-18 13-55-31

Your proposed improvement looks good. Please make a few improvements:

- Please extend the interface IStepSeriesSettings from IPointSeriesSettings and create an implementation StepSeriesSettings in a new package "org.eclipse.swtchart.extensions.stepcharts".

Bildschirmfoto vom 2020-03-18 13-56-56

- Adjust the comment in "IExtendedChart" - "createSeries(...)" by the type STEP option.
- Extend "AbstractExtendedChart" by the STEP option:

`
	private SeriesType getSeriesType(ISeriesSettings seriesSettings) {

		SeriesType seriesType = SeriesType.LINE; // Default
		if(seriesSettings instanceof IBarSeriesSettings) {
			seriesType = SeriesType.BAR;
		}
		//
		return seriesType;
	}`

- Create a specific StepChart in the package "org.eclipse.swtchart.extensions.stepcharts". User shall be enabled to use a StepChart without taking care of the underlying specific settings that need to be set, e.g. in a similar ways as the ScatterChart.

Please create also an example in "org.eclipse.swtchart.extensions.examples".

**Comment by eselmeister** [comment]
@yashTEF The checks are failing. Have you signed the ECA and set the "Signed-off" flag? The user email for the ECA and "Signed-off" flag must be the same.

**Comment by eselmeister** [comment]
Curiously, it worked before. Have you changed something? Username, email?

**Pull request closed without merging**
