### PR TITLE
Added code to render an option to the chart axis to set only required ticks

### PR DESCRIPTION
**Pull request by himanshu-balasamanta**
In many cases, the axis can have data only at integral values. In such cases, having Axis that has ticks at non-Integral points does not make the chart very presentable..

To set an Axis to have only Integer Ticks, integerDataPointAxis is to be enabled true.
Series such as BarSeries will almost always have this case with their X-Axis, and hence I have mentioned it in the constructor.

One may also use this with Y- axis by mentioning the following in the code..

`((Axis)chart.getAxisSet().getYAxis(0)).setIntegerDataPointAxis(true);`

The code has passed all test cases successfully. 

I shall be grateful if this pull request is not closed... And shall be glad to recieve suggestions as to furthur improvements..

Thanks in advance,
Himanshu

### CODE REVIEW

**Comment by himanshu-balasamanta** [comment]
BARCHART With BOTH X AND Y AXIS HAVING NON-INTEGER TICKS
BarChartBothNonInteger
BARCHART WITH X AXIS ONLY HAVING INTEGER TICKS
BarChartXAxisIntegerYNonInteger
BARCHART WITH X AXIS AND Y AXIS HAVING INTEGER TICKS ONLY...
BarChartBothIntegerAxes

**Comment by himanshu-balasamanta** [comment]
The code when used with equally spaced data points on the X-AXIS, will tick only at data points present in the XSeries. 
When used with Y-Axis, it will have tickStep as 1 or integral vaue more than 1.

**Comment by eselmeister** [comment]
@Himanshu-Balasamanta Your change looks good. Please also add the option to the IAxisSettings in the "org.eclipse.swtchart.extensions" package so that it can be used either directly or via the settings instance:

Have a look at "boolean reversed" as an example how it is initialized and used:
org.eclipse.swtchart.extensions.core.IAxisSettings

`	boolean isReversed();
	void setReversed(boolean reversed);`

Initialize
org.eclipse.swtchart.extensions.core.BaseChart

`	xAxisPrimary.setReversed(false);
	yAxisPrimary.setReversed(false);`

**Comment by himanshu-balasamanta** [comment]
Hello Sir,
I hope this is what you wanted. I have more ideas to implement, which I shall do a few days later maybe... If this is fine with you, do merge it...

**Comment by eselmeister** [comment]
@Himanshu-Balasamanta Please have a look at the following issues:

1) Format the source code before committing/pushing it. The source code style is included already. You have to activate the "Save Action" in the Eclipse settings.

Bildschirmfoto von 2020-03-23 06-09-04

2) Update the year in the copyright header of the source files to 2020, when changing code.

3) When extending the interfaces, please mark implementing methods with "@Override".

4) Setting the BarChart axis by default to IntegerDataPointAxis(true) leads to the problem, that e.g. the mass spectrum (bar series) charts can't be used anylonger.

Bildschirmfoto von 2020-03-23 05-58-36

I have set the option by default to "false", so that it needs to be activated on demand and existing code works as expected.

Bildschirmfoto von 2020-03-23 06-13-40

Please add a test case to show the "IntegerDataPointAxis(true)" option here:
org.eclipse.swtchart.extensions.examples.parts

Add a new part and link it to the fragment.e4xmi file.

Please test your code before committing it.

**Pull request merged**
